In [2]:
import pandas as pd

import numpy as np

df = pd.read_excel("Raisin_Dataset.xlsx")
print(df.head())

    Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea  \
0  87524       442.246011       253.291155      0.819738       90546
1  75166       406.690687       243.032436      0.801805       78789
2  90856       442.267048       266.328318      0.798354       93717
3  45928       286.540559       208.760042      0.684989       47336
4  79408       352.190770       290.827533      0.564011       81463

     Extent  Perimeter    Class
0  0.758651   1184.040  Kecimen
1  0.684130   1121.786  Kecimen
2  0.637613   1208.575  Kecimen
3  0.699599    844.162  Kecimen
4  0.792772   1073.251  Kecimen

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Area             900 non-null    int64
 1   MajorAxisLength  900 non-null    float64
 2   MinorAxisLength  900 non-null    float64
 3   Eccentricity     900 non-null    float64
 4   ConvexArea       900 non-null    int64
 5   Extent           900 non-null    float64
 6   Perimeter        900 non-null    float64
 7   Class            900 non-null    object
dtypes: float64(5), int64(2), object(1)
memory usage: 56.4+ KB

In [4]:
df=pd.get_dummies(df, columns=['Class'], drop_first=True)
df

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class_Kecimen
0,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.040,True
1,75166,406.690687,243.032436,0.801805,78789,0.684130,1121.786,True
2,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575,True
3,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162,True
4,79408,352.190770,290.827533,0.564011,81463,0.792772,1073.251,True
...,...,...,...,...,...,...,...,...
895,83248,430.077308,247.838695,0.817263,85839,0.668793,1129.072,False
896,87350,440.735698,259.293149,0.808629,90899,0.636476,1214.252,False
897,99657,431.706981,298.837323,0.721684,106264,0.741099,1292.828,False
898,93523,476.344094,254.176054,0.845739,97653,0.658798,1258.548,False
899,85609,512.081774,215.271976,0.907345,89197,0.632020,1272.862,False

In [5]:
target = df["Class_Kecimen"].astype(int)
target

0      1
1      1
2      1
3      1
4      1
      ..
895    0
896    0
897    0
898    0
899    0
Name: Class_Kecimen, Length: 900, dtype: int32

In [6]:
X = df.drop("Class_Kecimen", axis=1)
X

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter
0,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.040
1,75166,406.690687,243.032436,0.801805,78789,0.684130,1121.786
2,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575
3,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162
4,79408,352.190770,290.827533,0.564011,81463,0.792772,1073.251
...,...,...,...,...,...,...,...
895,83248,430.077308,247.838695,0.817263,85839,0.668793,1129.072
896,87350,440.735698,259.293149,0.808629,90899,0.636476,1214.252
897,99657,431.706981,298.837323,0.721684,106264,0.741099,1292.828
898,93523,476.344094,254.176054,0.845739,97653,0.658798,1258.548
899,85609,512.081774,215.271976,0.907345,89197,0.632020,1272.862